# Generated by Django 5.2.8 on 2025-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='live_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
