# Generated by Django 5.2.8 on 2025-11-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='errors_erro_created_724838_idx',
            old_name='errors_error_created_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='errors_erro_severit_62b5f1_idx',
            old_name='errors_error_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='errors_erro_error_t_dfeacc_idx',
            old_name='errors_error_type_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='errors_erro_resolve_658429_idx',
            old_name='errors_error_resolved_idx',
        ),
    ]
