# Generated by Django 5.2.8 on 2025-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp_send_error_otp_send_result_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
