# Generated by Django 5.2.8 on 2025-11-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_celery_task_id_otp_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='message_id',
        ),
    ]
