# Generated by Django 5.2.8 on 2025-11-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_otp_celery_task_id_remove_otp_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='license_document',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_back',
            field=models.FileField(blank=True, null=True, upload_to='licenses/back/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_front',
            field=models.FileField(blank=True, null=True, upload_to='licenses/front/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_issued_state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='state',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_back',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/back/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_front',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/front/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_interior',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/interior/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_side',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/side/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
