# Generated by Django 5.2.8 on 2025-11-20 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('validation', 'Validation Error'), ('authentication', 'Authentication Error'), ('authorization', 'Authorization Error'), ('network', 'Network Error'), ('database', 'Database Error'), ('server', 'Server Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_f90db7_idx'), models.Index(fields=['error_type', '-created_at'], name='notificatio_error_t_925ee0_idx'), models.Index(fields=['severity', '-created_at'], name='notificatio_severit_90a268_idx')],
            },
        ),
    ]
